#spring.application.name=tour-service
#spring.datasource.url="jdbc:mysql://localhost:3306/tour-service"
#spring.datasource.username=root

server:
  port: 8080
  servlet:
    context-path: /tours

spring:
  application:
    name: tour-service
  datasource:
    url: "jdbc:mysql://localhost:3306/tour-service"
    username: root
    password: root
